server:
  port: 19999


dubbo:
  registry:
    address: zookeeper://10.1.175.37:2181
    session: 30000
    timeout: 100000
  scan:
    base-packages: com.niezhiliang.dubbo.provider.rpc
  provider:
    timeout: 60000
    version: 1.0
  protocol:
    name: dubbo
    serialization: java
    port: -1
    threads:
  consumer:
    version: 1.0
  application:
    name: provider
spring:
  datasource:
    name: test
    url: jdbc:mysql://223.223.223.248:3306/chenmg_test
    username: dbadmin
    password: zhyjy@DB123
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml
